actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
avgRunTime: 5
avgRunTimeDisplay: 5 Seconds
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_sleep
firstRun: 2022-01-28 08:38:37 -0500
holdResources: false
lastRun: 2023-07-31 19:30:16 -0400
lastRunTime: 5
lastRunTimeDisplay: 5 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 5
maxRunTimeDisplay: 5 Seconds
minRunTime: 5
minRunTimeDisplay: 5 Seconds
name: Utt Task B2
notes: []
opswiseGroups:
- Utt
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 5227
runTime: 26135
sleepAmount: '5'
sleepDayConstraint: None
sleepDuration: 00:00:00:00
sleepTime: 00:00
sleepType: Seconds
startHeld: false
startHeldReason: null
summary: This task runs for 5 seconds only on Mon/Wed/Fri
sysId: f9eb38b170dd49568be1d07b65aeeb25
timeZonePref: -- System Default --
type: taskSleep
userEstimatedDuration: null
variables: []
version: 7
virtualResources: []
