actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations:
  - agent: null
    agentCluster: null
    agentClusterVar: null
    agentVar: null
    description: null
    execCommand: Force Finish
    execCriteria: Newest Active Instance
    execId: null
    execLookupOption: Instance Name
    execName: Utt Fail Task
    execWorkflowName: Utt Workflow A
    execWorkflowNameCond: Equals
    exitCodes: null
    limit: null
    notificationOption: Operation Failure
    notifyOnEarlyFinish: false
    notifyOnLateFinish: false
    notifyOnLateStart: false
    notifyOnProjectedLate: false
    operation: Run Task Instance Command
    overrideTriggerDateOffset: null
    overrideTriggerDateTime: false
    overrideTriggerTime: 00:00
    status: 'Finished,

      Success'
    sysId: 565676f8f475425bb45b84be6a2bb181
    task: null
    taskLimitType: Unlimited
    taskVar: null
    trigger: null
    triggerVar: null
    variables: []
    variablesUnresolved: false
    virtualResource: null
    virtualResourceVar: null
avgRunTime: 90
avgRunTimeDisplay: 1 Minute 30 Seconds
cpDuration: null
cpDurationUnit: Minutes
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_sleep
firstRun: 2022-01-28 09:16:21 -0500
holdResources: false
lastRun: 2023-08-01 03:16:45 -0400
lastRunTime: 90
lastRunTimeDisplay: 1 Minute 30 Seconds
lfDayConstraint: None
lfDuration: 00:00:01:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 120
maxRunTimeDisplay: 2 Minutes 0 Seconds
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: Utt Correct Fail Task
notes: []
opswiseGroups:
- Utt
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 9356
runTime: 841981
sleepAmount: '90'
sleepDayConstraint: None
sleepDuration: 00:00:00:00
sleepTime: 00:00
sleepType: Seconds
startHeld: false
startHeldReason: null
summary: This task corrects the failed task
sysId: 3f6fed62f06941eea49217e80c2b9488
timeZonePref: -- System Default --
type: taskSleep
userEstimatedDuration: null
variables: []
version: 10
virtualResources: []
