actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
avgRunTime: 77009
avgRunTimeDisplay: 21 Hours 23 Minutes 29 Seconds
calculateCp: false
calendar: null
cpDuration: null
cpDurationUnit: Minutes
criticalEndpoints: []
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_workflow
firstRun: 2023-05-24 13:35:00 -0400
holdResources: false
lastRun: 2023-07-31 06:02:00 -0400
lastRunTime: 59220
lastRunTimeDisplay: 16 Hours 27 Minutes 0 Seconds
layoutOption: -- None --
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxRunTime: 87787
maxRunTimeDisplay: 1 Day 0 Hour 23 Minutes 7 Seconds
minRunTime: 163
minRunTimeDisplay: 2 Minutes 43 Seconds
name: A Workflow
notes: []
numberOfTasks: 1
opswiseGroups: []
overrideCalendar: false
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 70
runCriteria: []
runTime: 5390630
skippedOption: Show Skipped
startHeld: false
startHeldReason: null
stepActions: []
stepConditions: []
summary: null
sysId: aa75e13137894d8598d1df8cc45c0538
timeZonePref: -- System Default --
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskWorkflow
userEstimatedDuration: null
variables: []
version: 2
virtualResources: []
workflowEdges: []
workflowVertices:
- alias: null
  task:
    value: Wait to Start
  vertexId: '2'
  vertexX: '31'
  vertexY: '30'
