actions:
  abortActions: []
  emailNotifications: []
  setVariableActions: []
  snmpNotifications: []
  systemOperations: []
agent: s3468talv
agentCluster: null
agentClusterVar: null
agentVar: null
avgRunTime: 1011
avgRunTimeDisplay: 16 Minutes 51 Seconds
broadcastCluster: null
broadcastClusterVar: null
byPercentage: null
byScale: 1024
bySize: null
cpDuration: null
cpDurationUnit: Minutes
credentials: null
credentialsVar: null
customField1:
  label: null
  value: null
customField2:
  label: null
  value: null
efDayConstraint: None
efDuration: 00:00:00:00
efEnabled: false
efNthAmount: 5
efOffsetDuration: null
efOffsetDurationUnit: Minutes
efOffsetPercentage: 0
efOffsetType: Percentage
efTime: 00:00
efType: Time
exclusiveTasks: []
exclusiveWithSelf: false
executionRestriction: None
exportReleaseLevel: 7.3.0.0
exportTable: ops_task_file_monitor
fileGroup: null
fileName: Utt
fileOwner: null
firstRun: 2022-01-28 07:42:56 -0500
fmtype: Created
holdResources: false
lastRun: 2023-08-01 03:30:06 -0400
lastRunTime: 905
lastRunTimeDisplay: 15 Minutes 5 Seconds
lfDayConstraint: None
lfDuration: 00:00:00:00
lfEnabled: false
lfNthAmount: 5
lfOffsetDuration: null
lfOffsetDurationUnit: Minutes
lfOffsetPercentage: 0
lfOffsetType: Percentage
lfTime: 00:00
lfType: Time
logLevel: Inherited
lsDayConstraint: None
lsDuration: 00:00:00:00
lsEnabled: false
lsNthAmount: 5
lsTime: 00:00
lsType: Time
maxFiles: null
maxRunTime: 175506
maxRunTimeDisplay: 2 Days 0 Hour 45 Minutes 6 Seconds
minFileScale: Bytes
minFileSize: '2'
minRunTime: 0
minRunTimeDisplay: 0 Seconds
name: Utt File Monitor
notes: []
opswiseGroups:
- Utt
recursive: false
resPriority: 10
resolveNameImmediately: false
restrictionPeriod: None
restrictionPeriodAfterDate: null
restrictionPeriodAfterTime: null
restrictionPeriodBeforeDate: null
restrictionPeriodBeforeTime: null
restrictionPeriodDateList: []
retainSysIds: true
runCount: 9344
runTime: 9443677
scanForward: false
scanText: null
stableSeconds: null
startHeld: false
startHeldReason: null
summary: This is a file monitor task
sysId: 92fde60dc1874bad8101d3c3c2a17eda
timeZonePref: -- System Default --
toScale: 1024
toSize: null
triggerOnExist: true
twDelayAmount: null
twDelayDuration: 00:00:00:00
twDelayType: None
twWaitAmount: null
twWaitDayConstraint: None
twWaitDuration: 00:00:00:00
twWaitTime: 00:00
twWaitType: None
twWorkflowOnly: -- System Default --
type: taskFileMonitor
useRegex: false
userEstimatedDuration: null
variables: []
version: 7
virtualResources: []
